### ISSUE TITLE
'marker' in get_bucket needs to be quoted

### ISSUE THREAD

**Issue by thattommyhall** [SpectraLogic/ds3_python_sdk#64]
I am doing the following 

```python
def get_blackperl_files():
    result = {}
    step = 10000
    start_from = None
    while True:
        bucketContents = client.get_bucket(ds3.GetBucketRequest(bucketName, max_keys=step, marker=start_from))
        contents_list = bucketContents.result['ContentsList']
        for obj in contents_list:
            keyname = obj['Key']
            result[keyname] = obj
        if len(contents_list) < step:
            return result
        start_from = urllib.quote((contents_list[-1]['Key']))
```

But I think it's a bug, I should just be able to pass the key name w/o quoting.

**Comment by thattommyhall** [comment]
```
 $ python list.py 
starting from: None
starting from: Easy.pdf
starting from: Triathlon Training For Dummies(2008)BBS.pdf
Traceback (most recent call last):
  File "list.py", line 4, in <module>
    for n in get_blackperl_files().keys():
  File "/home/thattommyhall/Dropbox/Projects/redux/bfi-backup/helpers.py", line 42, in get_blackperl_files
    bucketContents = client.get_bucket(ds3.GetBucketRequest(bucketName, max_keys=step, marker=start_from))
  File "/home/thattommyhall/Dropbox/Projects/redux/bfi-backup/ds3/ds3.py", line 6713, in get_bucket
    return GetBucketResponse(self.net_client.get_response(request), request)
  File "/home/thattommyhall/Dropbox/Projects/redux/bfi-backup/ds3/ds3.py", line 5280, in __init__
    self.process_response(response)
  File "/home/thattommyhall/Dropbox/Projects/redux/bfi-backup/ds3/ds3.py", line 5348, in process_response
    self.__check_status_codes__([200])
  File "/home/thattommyhall/Dropbox/Projects/redux/bfi-backup/ds3/ds3.py", line 5302, in __check_status_codes__
    raise RequestFailed(err, ds3_error)
ds3.ds3network.RequestFailed: Return Code: Expected [200] - Received 505 
 Code=HTTP Version Not Supported 
 HttpError=505 
 None
```

**Comment by thattommyhall** [comment]
```
 $ python list.py 
starting from: None
starting from: Easy.pdf
starting from: Triathlon Training For Dummies(2008)BBS.pdf
Traceback (most recent call last):
  File "list.py", line 4, in <module>
    for n in get_blackperl_files().keys():
  File "/home/thattommyhall/backup/helpers.py", line 42, in get_blackperl_files
    bucketContents = client.get_bucket(ds3.GetBucketRequest(bucketName, max_keys=step, marker=start_from))
  File "/home/thattommyhall/backup/ds3/ds3.py", line 6713, in get_bucket
    return GetBucketResponse(self.net_client.get_response(request), request)
  File "/home/thattommyhall/backup/ds3/ds3.py", line 5280, in __init__
    self.process_response(response)
  File "/home/thattommyhall/backup/ds3/ds3.py", line 5348, in process_response
    self.__check_status_codes__([200])
  File "/home/thattommyhall/backup/ds3/ds3.py", line 5302, in __check_status_codes__
    raise RequestFailed(err, ds3_error)
ds3.ds3network.RequestFailed: Return Code: Expected [200] - Received 505 
 Code=HTTP Version Not Supported 
 HttpError=505 
 None
```

**Comment by rpmoore** [comment]
Is the stack trace a result of not escaping the key?

**Comment by thattommyhall** [comment]
yeah, without `urllib.quote` that's what happens

**Comment by rpmoore** [comment]
We will get a fix for this out after the holiday.  Thanks for reporting!
